<?php

namespace curriculum\model\proxies\__CG__\curriculum\model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcademicQualifications extends \curriculum\model\AcademicQualifications implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'dateOfBegin', 'dateOfFinish', 'profile', 'instituteOfEducation', 'localeStrings'];
        }

        return ['__isInitialized__', 'id', 'dateOfBegin', 'dateOfFinish', 'profile', 'instituteOfEducation', 'localeStrings'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AcademicQualifications $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLocaleStrings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocaleStrings', []);

        return parent::getLocaleStrings();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocaleStrings($localeStrings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocaleStrings', [$localeStrings]);

        return parent::setLocaleStrings($localeStrings);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBegin(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBegin', []);

        return parent::getDateOfBegin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBegin(\DateTime $dateOfBegin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBegin', [$dateOfBegin]);

        return parent::setDateOfBegin($dateOfBegin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfFinish(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfFinish', []);

        return parent::getDateOfFinish();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfFinish(\DateTime $dateOfFinish)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfFinish', [$dateOfFinish]);

        return parent::setDateOfFinish($dateOfFinish);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile(): \curriculum\model\Profile
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(\curriculum\model\Profile $profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstituteOfEducation(): \curriculum\model\InstituteOfEducation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstituteOfEducation', []);

        return parent::getInstituteOfEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstituteOfEducation(\curriculum\model\InstituteOfEducation $instituteOfEducation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstituteOfEducation', [$instituteOfEducation]);

        return parent::setInstituteOfEducation($instituteOfEducation);
    }

}
